# Site
repository: gokulrajeeve/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Gokul Rajeeve
title: B.Tech Mechatronics
email: me@gokulrajeeve.com
website: gokulrajeeve.com

# Dark Mode (true/false/never)
darkmode: false

# Social links

linkedin_username: gokulrajeeve


# Additional icon links
additional_links:
- title: gokulrajeeve.com
  icon: fas fa-globe
  url: https://gokulrajeeve.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Gokul Rajeeve and I completed BTech in Mechatronics from Manipal Institute of Technology in 2020.  I am a technology enthusiast and would like to get involved in building systems.

  My interest areas are: <mark>Programming</mark>, <mark>Data Science</mark> and <mark>Robotics</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Manipal Institute of Technology
        caption: 2016 - 2020
        sub_title: BTech. in Mechatronic                                                                                                                 
        quote: >
          Manipal University, Manipal, Karnataka
        description: | # this will include new lines to allow paragraphs
          **Related Courses:** AI, Machine Vision and Image Processing, Robotic Dynamics and Control, Robotic Path Planning, Hydraulic and Pneumatic system, Essentials of Information Technology, Microcontroller Based System Design, Mechatronic System designs
  - title: Technical Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Langauges:**    C++, Python, MATLAB 
      - **Web Technologies:**    HTML5, CSS3, Static Site Generators (Jekyll) 
      - **Others:**    MySQL, DBMS, CAD, Lathe Operation, PLC, CNC , RHINO
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Can adapt to diverse team environments
      - Proficient in both oral and written communication skills
      - Quick learner
      - Problem solving and analytical skills
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Anand Track and Field
        link: 
        # link_text: boringcompany.com
        sub_title: 
        caption: 
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            -	Co-ordinated with design team to develop CAD models. All models required to be within industrial guidelines.
                - Discuses.
                - Take off board.
                - Hurdle stands.
            -	Provided design improvements to brand logo for branding via CNC to accommodate provided dimensions.
            -	Participated in manufacturing processes using lathes such as turning and facing for products.
            -	Aided storage and packaging departments by providing more ideal storage and listing options for better workflow.
      - layout: left
        title: Delphi Technologies
        link: 
        # link_text: boringcompany.com
        sub_title: 
        caption: 
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            -	Supported validation and inspection engineers for inspection of connectors used in commercial cars. 
            -	Learned about various electronic components for automotive manufactured at the factory.
            -	Built an understanding how connectors work within hybrid electric vehicles and its necessity.
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Designing and building a fully functional RC car for competitive racing
        link: 
        # link_text: boringcompany.com
        sub_title: 
        caption: 
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            -	Successfully coordinated with team mates to deliver fully functional RC assembling and programming the car from scratch.
            -	Worked on the transmitter-receiver to achieve fully wireless control of each motor independently.	
            -	Debugged the circuitry to assure complete functionality. 
            -	Developed working logic for RC car using differential drive algorithm.
      - layout: left
        title: Design and Analysis of low-cost haptic paddle for academic application
        link: 
        # link_text: boringcompany.com
        sub_title: 
        caption: 
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            -	Haptic paddle was designed to achieve bidirectional haptic force feedback in both X and Y axis. This 2 DOF device allows the user to experience a wide range of virtual scenarios considering the single axis haptic paddle. We built an understanding of the impact of such devices when integrated in course curriculums to aid students with hand-on experience.
            -	Kinematic equations were calculated, and position feedback was achieved.
            -	Co-ordinated with team mate to develop codes and design paddle.
            -	Carried out virtual tests to discover errors and optimize device.
      - layout: left
        title: Handwritten character recognition with Neural Network
        link: 
        # link_text: boringcompany.com
        sub_title: 
        caption: 
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            -	Streaming alphabets via camera in real time and obtaining optical character recognition of the English alphabets using OpenCV.
            -	Dataset was split into train set to train model and test set to evaluate performance of the model.
            -	Worked on SVM for data classification.
            -	Each iteration yielded favorable results, adding successful iterations to test set to perfect the neural network.
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
